# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class GhSource < Formula
  desc "Plugin manager for people who don't like plugin managers"
  homepage "https://github.com/Yarden-zamir/gh-source"
  url "https://github.com/Yarden-zamir/gh-source/archive/v0.0.15.tar.gz"
  sha256 "c1342c425fe599e5a6fdcb614c23cc74ac83e55de80ae6a841c14b37a245abbd"
  license "MIT"

  depends_on "gh"

  def install
    pkgshare.install "gh-source.zsh"
pkgshare.install "zsh-completion"
  end
end
