# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class GhSource < Formula
  desc "Plugin manager for people who don't like plugin managers"
  homepage "https://github.com/Yarden-zamir/gh-source"
  url "https://github.com/Yarden-zamir/gh-source/archive/v0.0.6.tar.gz"
  sha256 "05817477a0e319fff28354a3505dd71f03d1bea9ef4b3e2f5f4c0e01105aada5"
  license "MIT"

  depends_on "gh"

  def install
    bin.install gh-source.zsh
libexec.install Dir["*"]
  end
end
