# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Wrap < Formula
  desc "Generates 'wraps' for functions in any language using 'processors'"
  homepage "https://github.com/Yarden-zamir/WRAP"
  url "https://github.com/Yarden-zamir/WRAP/archive/v0.2.18.tar.gz"
  sha256 "126964b14610ea3993cad006a29d0532cc2fc08674af29e920baa1afbddb1b0d"

  depends_on "python@3.10"

  def install
    bin.install "wrap.py" => "wrap"
FileUtils.cp_r "base_processors/generic_argparse_processor.py", "wrap_generic_argparse_processor.py"
bin.install "wrap_generic_argparse_processor.py"
bin.install "base_processors"
bin.install "example1"
  end
end
