# enable automerge on pull requests that have the label "auto-merge"
name: automerge

on:
  pull_request_target:
  
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR description
        uses: actions/github-script@v3
        id: pr
        with:
          github-token: ${{ github.token }}
          script: |
            const pr = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            })
            return pr.data.body
      - name: Label PR as auto-merge on tap repository
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ contains(steps.pr.outputs.result, '/add-label auto-merge') }}
        with:
          labels: auto-merge
          github_token: ${{ github.token }}
          number: ${{ github.event.pull_request.number }}

  enable_automerge:
    needs: label
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'auto-merge') }}
    steps:
    - uses: actions/checkout@v3
    - name: Enable Pull Request Automerge
      run: gh pr merge --merge --auto "1"
      env:
        GH_TOKEN: ${{ github.token }}

